"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

const mins = (s: string) => { const [h,m] = s.slice(0,5).split(":").map(Number); return h*60+m; }; const clock = (n:number) => `${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`;
export default function CalendarDay({ date, settings, tableId, bookings, blocks }: { date:string; settings:{opening_time:string;closing_time:string;booking_interval_minutes:number}; tableId:number; bookings:any[]; blocks:any[] }) {
  const router = useRouter(); const [error,setError]=useState(""); const slots=[]; for(let m=mins(settings.opening_time);m<mins(settings.closing_time);m+=settings.booking_interval_minutes){ const b=bookings.find(x=>m<mins(x.end_time)&&m+settings.booking_interval_minutes>mins(x.start_time)); const block=blocks.find(x=>m<mins(x.end_time)&&m+settings.booking_interval_minutes>mins(x.start_time)); slots.push({time:clock(m), text:block ? `Blocked — ${block.reason}` : b ? `${b.status.replaceAll('_',' ')} — ${b.customers?.name}` : 'Available'}); }
  async function block(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const response=await fetch('/api/admin/blocked-times',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({table_id:tableId,date,start_time:form.get('start'),end_time:form.get('end'),reason:form.get('reason')})});const body=await response.json();if(!response.ok)return setError(body.error);router.refresh();}
  return <div className="booking-grid"><section className="card"><form className="filters"><input type="date" name="date" value={date} onChange={e=>router.push(`/admin/calendar?date=${e.target.value}`)}/></form>{slots.map(s=><div className="summary-line" style={{padding:'13px 0',borderBottom:'1px solid var(--line)'}} key={s.time}><strong>{s.time}</strong><span>{s.text}</span></div>)}</section><aside className="card"><h2 style={{marginBottom:18}}>Block time</h2><form onSubmit={block} style={{display:'grid',gap:12}}><label className="field">Start<input name="start" type="time" required step="3600"/></label><label className="field">End<input name="end" type="time" required step="3600"/></label><label className="field">Reason<input name="reason" required placeholder="Maintenance"/></label>{error&&<div className="notice">{error}</div>}<button className="button">Block time</button></form></aside></div>;
}
